use super::*;

pub(crate) fn apply_demo_fixture(app: &mut App) {
    let now = chrono::Utc::now();
    let now_str = now.to_rfc3339();

    let attempt = crate::state::ReleaseAttempt {
        id: 42,
        project_id: release::DEFAULT_RELEASE_PROJECT_ID,
        ref_name: "main".into(),
        sha: "9c3f2d4e0b9f5d1d7cc8".into(),
        version: "v3.0.1-demo".into(),
        upstream_pipeline_id: Some(8_012),
        upstream_status: "success".into(),
        release_pipeline_id: Some(8_013),
        release_pipeline_status: Some("running".into()),
        production_pipeline_id: Some(8_014),
        production_pipeline_status: Some("pending".into()),
        canary_status: "in-flight".into(),
        canary_started_at: Some(now_str.clone()),
        canary_finished_at: None,
        canary_note: Some("Evaluating telemetry and E2E readiness".into()),
        created_at: now_str.clone(),
        updated_at: now_str.clone(),
    };

    let release_status = release::ReleaseAttemptView {
        attempt: attempt.clone(),
        release_dir: "target/demo-release".into(),
        canary_state_path: "artifacts/canary.state".into(),
        gate_remote_canary_path: "artifacts/remote-canary.txt".into(),
        gate_canary_e2e_path: "artifacts/canary-e2e.txt".into(),
        gate_canary_telemetry_path: "artifacts/canary-telemetry.txt".into(),
        telemetry_diag_path: "artifacts/telemetry-diag.json".into(),
        canary_state: "in-flight".into(),
        eligibility: "high-confidence".into(),
        phase: Some("validation".into()),
        detail: Some("Demo release is active and collecting proof.".into()),
        state_status: Some("running".into()),
        has_remote_gate: true,
        has_telemetry_gate: true,
        has_e2e_gate: true,
        has_telemetry_diag: true,
        release_identity_ok: true,
        canary_public_url: Some("https://example.invalid/jeryu/demo-canary".into()),
    };

    let flow_jobs = vec![
        demo_job_event(
            9_001,
            "success",
            "policy-admission",
            "trusted",
            "sys-a1",
            Some(1.6),
            now_str.clone(),
        ),
        demo_job_event(
            9_002,
            "running",
            "build-image",
            "trusted",
            "sys-a2",
            Some(0.4),
            now_str.clone(),
        ),
        demo_job_event(
            9_003,
            "pending",
            "integration-tests",
            "trusted",
            "sys-a3",
            None,
            now_str.clone(),
        ),
        demo_job_event(
            9_004,
            "failed",
            "security-gate",
            "security",
            "sys-s1",
            Some(0.8),
            now_str.clone(),
        ),
        demo_job_event(
            9_005,
            "running",
            "e2e-canary",
            "trusted",
            "sys-a4",
            Some(0.9),
            now_str.clone(),
        ),
    ];
    let flow_graph = crate::tui::flow::builder::build_graph(8_013, flow_jobs.clone());
    let progress_pct: u16 = 68;

    let flow = crate::tui::flow::FlowSnapshot {
        generated_at: now,
        gitlab_online: true,
        active_pipelines: vec![crate::tui::flow::PipelineFlow {
            pipeline_id: 8_013,
            project_id: release::DEFAULT_RELEASE_PROJECT_ID,
            ref_name: "main".into(),
            sha: Some("9c3f2d4e0b9f5d1d7cc8".into()),
            status: "running".into(),
            graph: flow_graph,
            current_blocker: Some(9_004),
            critical_path: vec![9_002, 9_003, 9_004],
            eta: Some(crate::tui::flow::EtaEstimate {
                remaining_secs: 380,
                confidence: crate::tui::flow::EtaConfidence::Medium,
                reason: "security gate remediation path may be needed".into(),
            }),
            progress_pct,
        }],
        outdated: false,
        last_non_empty_at: Some(now),
        selected_pipeline_id: Some(8_013),
        release: Some(release_status.clone()),
        pools: vec![
            demo_pool(
                "trusted",
                9001,
                "token-trusted",
                "linux,x86_64,trusted",
                2,
                10,
                4,
                4,
                "trusted",
            ),
            demo_pool(
                "security",
                9002,
                "token-security",
                "linux,x86_64,security",
                1,
                4,
                2,
                2,
                "restricted",
            ),
            demo_pool(
                "research",
                9003,
                "token-research",
                "linux,arm64,research",
                1,
                3,
                1,
                1,
                "experimental",
            ),
        ],
        active_containers: 11,
        cache_metrics: crate::tui::flow::CacheMetrics {
            hot_usage_bytes: 24_311_008,
            hits: 1_102,
            objects: 2_900,
            singleflight_coalesced: 72,
            hit_ratio: 0.88,
            misses: 148,
            requests: 1_250,
        },
    };

    app.state = TuiStateSnapshot {
            pools: vec![
                Pool {
                    name: "trusted".into(),
                    gitlab_runner_id: 9001,
                    auth_token: "token-trusted".into(),
                    tags: "linux,x86_64,trusted".into(),
                    executor: "docker".into(),
                    min_warm: 2,
                    max_managers: 10,
                    concurrent: 4,
                    request_concurrency: 4,
                    paused: false,
                    trust_tier: "trusted".into(),
                },
                Pool {
                    name: "security".into(),
                    gitlab_runner_id: 9002,
                    auth_token: "token-security".into(),
                    tags: "linux,x86_64,security".into(),
                    executor: "docker".into(),
                    min_warm: 1,
                    max_managers: 4,
                    concurrent: 2,
                    request_concurrency: 2,
                    paused: false,
                    trust_tier: "restricted".into(),
                },
            ],
            gitlab_ready: true,
            active_containers: 11,
            recent_jobs: flow_jobs,
            pipelines: vec![
                PipelineMetrics {
                    pipeline: demo_pipeline(8_013, "running", now_str.clone()),
                    total: 5,
                    completed: 2,
                },
                PipelineMetrics {
                    pipeline: demo_pipeline(8_014, "pending", now_str.clone()),
                    total: 3,
                    completed: 0,
                },
            ],
            flow,
            live_log: LiveLogState {
                target: Some(LogTarget {
                    project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                    job_id: 9_002,
                }),
                text: "[demo] security gate failed due to outdated artifact cache\n[demo] remediation required with clean cache namespace\n".into(),
                updated_at: Some(now_str.clone()),
                error: None,
                outdated: false,
            },
            hot_cache_usage_bytes: 2_340_000_000,
            cache_hits: 1_102,
            cache_objects_count: 2_900,
            proxy_healthy: true,
            registry_healthy: true,
            mirror_enabled: true,
            ca_mounted: true,
            singleflight_requests: 72,
            hit_ratio: 0.88,
            miss_count: 148,
            total_requests: 1_250,
            active_taint_count: 1,
            detonation_breaches: 0,
            cold_execution_downgrades: 0,
            cas_disk_bytes: 11_500_000,
            crate_cache_disk_bytes: 8_900_000,
            storage_breakdown: StorageBreakdown {
                docker_images_bytes: 7_000_000,
                docker_volumes_bytes: 3_000_000,
                docker_build_cache_bytes: 5_000_000,
                cas_bytes: 11_500_000,
                crate_cache_bytes: 8_900_000,
                runner_data_bytes: 2_600_000,
                git_repos_bytes: 1_200_000,
                rust_target_bytes: 2_300_000,
                state_store_bytes: 450_000,
                total_disk_bytes: 45_000_000,
                disk_available_bytes: 120_000_000,
            },
            pipeline_eta: Some("~6m".into()),
            pipeline_progress: progress_pct,
            release_status: Some(release_status.clone()),
            release_status_generated_at: Some(now_str.clone()),
            test_bottlenecks_avg: vec![
                crate::state::TestBottleneck {
                    test_name: "integration::cache_layer".into(),
                    avg_duration_ms: 7_200.0,
                    latest_duration_ms: 7_450,
                    count: 12,
                },
                crate::state::TestBottleneck {
                    test_name: "unit::scheduler".into(),
                    avg_duration_ms: 1_100.0,
                    latest_duration_ms: 1_020,
                    count: 24,
                },
                crate::state::TestBottleneck {
                    test_name: "e2e::release_path".into(),
                    avg_duration_ms: 18_000.0,
                    latest_duration_ms: 18_720,
                    count: 4,
                },
            ],
            test_bottlenecks_latest: vec![
                crate::state::TestBottleneck {
                    test_name: "e2e::release_path".into(),
                    avg_duration_ms: 18_000.0,
                    latest_duration_ms: 18_720,
                    count: 4,
                },
                crate::state::TestBottleneck {
                    test_name: "integration::policy".into(),
                    avg_duration_ms: 5_300.0,
                    latest_duration_ms: 5_910,
                    count: 9,
                },
                crate::state::TestBottleneck {
                    test_name: "security::secret_scan".into(),
                    avg_duration_ms: 6_200.0,
                    latest_duration_ms: 6_000,
                    count: 6,
                },
            ],
            last_sync_at: Some(now),
            inspector_capsule: Some(crate::capsule::FailureCapsule {
                job_id: 9_004,
                pipeline_id: Some(8_013),
                project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                stage: "security".into(),
                exit_code: 1,
                commit_sha: "9c3f2d4e0b9f5d1d7cc8".into(),
                ref_name: "main".into(),
                working_directory: "/workspace".into(),
                log_snippet: "security gate timed out in artifact verification".into(),
                repro_script: "./tools/run-security-gate.sh".into(),
                environment: std::collections::HashMap::new(),
                failure_kind: "timeout".into(),
                summary: "security gate timeout on canary validation".into(),
                superseded_by_sha: None,
                requeued_from_job_id: None,
            }),
            inspector_job_id: Some(9_004),
            recent_evidence: vec![
                demo_evidence_record(
                    11,
                    "vti_validation",
                    9_003,
                    "test",
                    "ok",
                    "{\"scope\": \"tests\", \"cache\": \"hit\"}",
                    now_str.clone(),
                ),
                demo_evidence_record(
                    12,
                    "secret_audit",
                    9_001,
                    "prepare",
                    "compliant",
                    "{\"vault\": \"rotation_ok\"}",
                    now_str.clone(),
                ),
            ],
            secret_audit_events: vec![
                demo_secret_audit_event(
                    21,
                    "release",
                    "rotated",
                    "release token rotated for canary context",
                    now_str.clone(),
                ),
                demo_secret_audit_event(
                    22,
                    "agent",
                    "fetched",
                    "agent bootstrap secret requested",
                    now_str.clone(),
                ),
            ],
            agent_pipelines: vec![
                demo_pipeline(8_013, "running", now_str.clone()),
                TrackedPipeline {
                    pipeline_id: 8_014,
                    project_id: release::DEFAULT_RELEASE_PROJECT_ID,
                    ref_name: "agent/repair-hypothesis".into(),
                    sha: "e8f2d2b77a11".into(),
                    status: "success".into(),
                    updated_at: now_str.clone(),
                },
            ],
            recent_audit_events: vec![
                crate::state::EventLog {
                    id: 501,
                    event_type: "capability.granted".into(),
                    timestamp: now_str.clone(),
                    project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                    job_id: Some(9_001),
                    actor: "ci-bot".into(),
                    payload: "{\"action\": \"run_validation\"}".into(),
                },
                crate::state::EventLog {
                    id: 502,
                    event_type: "vti.receipt".into(),
                    timestamp: now_str.clone(),
                    project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                    job_id: Some(9_003),
                    actor: "validator".into(),
                    payload: "{\"status\": \"selected\", \"selector\": \"safe\"}".into(),
                },
                crate::state::EventLog {
                    id: 503,
                    event_type: "merge_gate.blocked".into(),
                    timestamp: now_str.clone(),
                    project_id: Some(release::DEFAULT_RELEASE_PROJECT_ID),
                    job_id: Some(9_004),
                    actor: "gatekeeper".into(),
                    payload: "{\"reason\": \"security_gate_failed\"}".into(),
                },
            ],
            recent_git_events: vec![],
            runner_feeds: vec![
                RunnerFeed {
                    runner_name: "trusted-01".into(),
                    job_id: 9_002,
                    job_name: "build-image".into(),
                    pipeline_id: 8_013,
                    status: "running".into(),
                    elapsed_secs: 134.0,
                    log_tail: "[2026-05-02 23:04:12] Compiling jeryu v3.0.1\n[2026-05-02 23:04:13] Compiling tokio v1.40\n[2026-05-02 23:04:14]   warning: missing import `std::io`\n[2026-05-02 23:04:15] Compiling serde v1.0\n[2026-05-02 23:04:16] Compiling ratatui v0.29\n[2026-05-02 23:04:17] Finished `release` profile in 2m14s".into(),
                    updated_at: now_str.clone(),
                },
                RunnerFeed {
                    runner_name: "trusted-02".into(),
                    job_id: 9_005,
                    job_name: "e2e-canary".into(),
                    pipeline_id: 8_013,
                    status: "running".into(),
                    elapsed_secs: 87.0,
                    log_tail: "[2026-05-02 23:04:30] Running e2e test suite...\n[2026-05-02 23:04:31] test canary::smoke_health ... ok\n[2026-05-02 23:04:32] test canary::telemetry_check ... FAILED\n[2026-05-02 23:04:33]   Error: telemetry endpoint returned 503\n[2026-05-02 23:04:34] test canary::rollback_gate ... ok".into(),
                    updated_at: now_str.clone(),
                },
                RunnerFeed {
                    runner_name: "security-01".into(),
                    job_id: 9_004,
                    job_name: "security-gate".into(),
                    pipeline_id: 8_013,
                    status: "failed".into(),
                    elapsed_secs: 45.0,
                    log_tail: "[2026-05-02 23:03:50] Running security scan...\n[2026-05-02 23:03:52] Checking artifact signatures...\n[2026-05-02 23:03:55] ERROR: Artifact verification timed out\n[2026-05-02 23:03:55] FATAL: security gate failed".into(),
                    updated_at: now_str.clone(),
                },
            ],
            active_feed_index: 0,
            feed_cycle_tick: 0,
            feed_auto_cycle: true,
            pipeline_progress_view: Some(PipelineProgressView {
                pipeline_id: 8_013,
                ref_name: "main".into(),
                sha_short: "9c3f2d4e".into(),
                stages: vec![
                    StageProgress {
                        stage_name: "build".into(),
                        total_jobs: 2, completed_jobs: 2, running_jobs: 0, failed_jobs: 0,
                        status: "success".into(),
                        avg_duration_secs: Some(180.0), elapsed_secs: Some(134.0),
                    },
                    StageProgress {
                        stage_name: "test".into(),
                        total_jobs: 3, completed_jobs: 1, running_jobs: 1, failed_jobs: 0,
                        status: "running".into(),
                        avg_duration_secs: Some(300.0), elapsed_secs: Some(87.0),
                    },
                    StageProgress {
                        stage_name: "security".into(),
                        total_jobs: 2, completed_jobs: 0, running_jobs: 0, failed_jobs: 1,
                        status: "failed".into(),
                        avg_duration_secs: Some(60.0), elapsed_secs: Some(45.0),
                    },
                    StageProgress {
                        stage_name: "deploy".into(),
                        total_jobs: 1, completed_jobs: 0, running_jobs: 0, failed_jobs: 0,
                        status: "pending".into(),
                        avg_duration_secs: Some(120.0), elapsed_secs: None,
                    },
                    StageProgress {
                        stage_name: "e2e".into(),
                        total_jobs: 2, completed_jobs: 0, running_jobs: 1, failed_jobs: 0,
                        status: "running".into(),
                        avg_duration_secs: Some(240.0), elapsed_secs: Some(87.0),
                    },
                ],
                overall_pct: 47,
                eta_remaining_secs: Some(492),
                eta_confidence: "medium".into(),
                wall_clock_secs: 862,
                started_at: Some(now_str.clone()),
            }),
            event_ticker_offset: 0,
        };

    app.selected_job_index = 0;
    app.selected_pipeline_index = 0;
    app.selected_pool_index = 0;
    app.selected_test_index = 0;
    app.selected_test_history = None;
    app.selected_evidence_index = 0;
    app.test_view_mode = TestViewMode::Average;
    app.evidence_view_mode = EvidenceViewMode::Capsules;
    app.maximize_logs = false;
    app.log_scroll_offset = 0;
    app.follow_log_tail = true;
    app.command_palette_open = false;
    app.command_palette_query.clear();
    app.selected_palette_index = 0;
    app.tick_count = 0;
    app.log_target = Some(LogTarget {
        project_id: release::DEFAULT_RELEASE_PROJECT_ID,
        job_id: 9_002,
    });
    app.log_target_tx.send(app.log_target).ok();
    app.remember_selected_job();
}
